name: Build and publish nuget packages

on:
  release:
    types:
      - published

env:
  RELEASE_VERSION: ${{ github.event.release.tag_name }}

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: |
        dotnet pack src/Fun.ReactGesture/Fun.ReactGesture.fsproj --configuration Release --no-restore -o artifacts /p:Version=${{ env.RELEASE_VERSION }}
        dotnet pack src/Fun.ReactSpring/Fun.ReactSpring.fsproj --configuration Release --no-restore -o artifacts /p:Version=${{ env.RELEASE_VERSION }}

    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
      
    - name: Push nuget packages
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate -s https://api.nuget.org/v3/index.json
